name: CD (Docker Hub → EC2)

on:
  push:
    branches: [ "main" ]

concurrency:
  group: cd-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_BACKEND: docker.io/sumin19987766/coco-backend
  IMAGE_FRONTEND: docker.io/sumin19987766/coco-frontend
  TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push Backend
        uses: docker/build-push-action@v6
        with:
          context: ./yeezy
          file: ./yeezy/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_BACKEND }}:latest
            ${{ env.IMAGE_BACKEND }}:${{ env.TAG }}

      - name: Build & Push Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./shop-react
          file: ./shop-react/Dockerfile
          push: true
          build-args: |
            REACT_APP_API_URL=/api
          tags: |
            ${{ env.IMAGE_FRONTEND }}:latest
            ${{ env.IMAGE_FRONTEND }}:${{ env.TAG }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -euxo pipefail
            # repo가 없으면 클론, 있으면 최신으로 업데이트
            if [ -d /home/ubuntu/coco/.git ]; then
              git -C /home/ubuntu/coco fetch --all
              git -C /home/ubuntu/coco reset --hard origin/main
            else
              git clone https://github.com/leesumin7766/coco.git /home/ubuntu/coco
            fi

            cd /home/ubuntu/coco
            docker compose pull
            docker compose up -d
            docker image prune -f
